services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  service_provider-backend:
    build: ./services/service_provider
    ports:
      - "8083:8083"
    environment:
      - REDIS_HOST=redis

  issuer-backend:
    build: ./services/issuer
    ports:
      - "8082:8082"
    environment:
      - REDIS_HOST=redis

  identity-holder-backend:
    build: ./services/identity_holder
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis

  frontend-unsw-employer:
    build: ./app/ServiceProvider/UNSW-employer
    ports:
      - "3001:3001"
    depends_on:
      - service_provider-backend
      - issuer-backend
      - identity-holder-backend
    
  # frontend-unsw-housing:
  #   build: ./app/ServiceProvider/University-Housing/uni-housing
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - service_provider-backend
  #     - issuer-backend
  #     - identity-holder-backend

  frontend-unsw-exams:
    build: ./app/ServiceProvider/UNSW-exams
    ports:
      - "3003:3003"
    depends_on:
      - service_provider-backend
      - issuer-backend
      - identity-holder-backend

  expo-app:
    container_name: identity-owner-frontend
    build:
      context: ./app/IdentityOwner/walletapp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    command: npm start -- --port 8000
    environment:
      EXPO_DEV_TOOLS: "true"  # Enable Expo DevTools in the container
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - service_provider-backend
      - issuer-backend
      - identity-holder-backend

  frontend-issuer:
    container_name: issuer-frontend
    build:
      context: ./app/IdentityIssuer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container port 8000 to host port 8000
    command: npm start -- --port 3000
    environment:
      EXPO_DEV_TOOLS: "true"  # Enable Expo DevTools in the container
      NODE_ENV: development
    stdin_open: true
    tty: true
    depends_on:
      - service_provider-backend
      - issuer-backend
      - identity-holder-backend