version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: issuer
    expose:
      - '8082'
      - '8443'
    ports:
      - '8082:8082'
      - '8443:8443'
    extra_hosts:
      - "host.docker.internal:host-gateway"
