version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: issuer
    expose:
      - '8082'
    ports:
      - '8082:8082'
    command: npx ts-node src/index.ts
