version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: issuer
    stdin_open: true
    tty: true
    expose:
      - '8082'
    ports:
      - '8082:8082'
    command: bun run src/index.ts -f formats.json
