version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - .:/usr/app
    container_name: issuer
    expose:
      - '8082'
      - '8443'
    ports:
      - '8082:8082'
      - '8443:8443'