version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - ./src:/usr/src/app/src
    container_name: issuer
    expose:
      - '8082'
    ports:
      - '8082:8082'