version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    container_name: service_provider
    expose:
      - '8083'
    ports:
      - '8083:8083'
    extra_hosts:
      - "host.docker.internal:host-gateway"