version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - ./src:/usr/app/src
    container_name: service_provider
    expose:
      - '8083'
    ports:
      - '8083:8083'