version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: identity_holder
    expose:
      - '8081'
    ports:
      - '8081:8081'
    command: npx ts-node src/index.ts
