version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - ./src:/usr/src/app/src
    container_name: identity_holder
    expose:
      - '8081'
    ports:
      - '8081:8081'